[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/healthz"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
path = "/healthz"
timeout = 30
interval = 10
retries = 5
startPeriod = 30

[deploy.healthcheck.fallback]
command = "npm run start:health"
timeout = 60

[env]
NODE_ENV = "production"
SERVICE_TYPE = "backend"
PORT = "8080"

# Database variables should be set manually in Railway dashboard
# See RAILWAY_ENV_SETUP.md for instructions

# To deploy frontend as separate service:
# 1. Create new Railway service from same repo
# 2. Set SERVICE_TYPE=frontend
# 3. Set PORT=3000
# 4. Set healthcheckPath="/"