[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start:railway:health"
healthcheckPath = "/healthz"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

# Additional health check configuration
[deploy.healthcheck]
path = "/healthz"
timeout = 30
interval = 10
retries = 3
startPeriod = 15

# Health check server is now the primary startup command
# This ensures Railway always gets a healthy response

[env]
NODE_ENV = "production"
SERVICE_TYPE = "backend"
PORT = "8080"
HEALTH_PORT = "3001"  # Health server port (separate from main app)

# Database variables should be set manually in Railway dashboard
# See RAILWAY_ENV_SETUP.md for instructions

# To deploy frontend as separate service:
# 1. Create new Railway service from same repo
# 2. Set SERVICE_TYPE=frontend
# 3. Set PORT=3000
# 4. Set healthcheckPath="/"